volumes:
  postgres_data: {}
  pg-admin: {}

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - Ewe=value
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # networks:
    #   - web_network


  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_USERNAME : postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - db
    # networks:
    #   - web_network


  web:
    build: .
    restart: no
    # entrypoint: /bin/sh -c "while true; do sleep 1000; done"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - postgres_data:/var/lib/postgresql/data/
      - ./static:/code/static  # Map the static directory from host to container
    dns:
      - 8.8.8.8
    ports:
      - "8000:8000"
    depends_on:
          - db
    # networks:
    #   - web_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PROXY_URL=http://proton-privox:8080 # Use the service name as the hostname
      # - HTTP_PROXY=http://proton-privoxy:8118
      # - HTTPS_PROXY=http://proton-privoxy:8118
      - Ewe=value
