# Generated by Django 5.0.6 on 2024-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumbleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumble_video_title', models.CharField(max_length=200)),
                ('rumble_video_description', models.TextField(null=True)),
                ('rumble_video_url', models.URLField(null=True)),
                ('rumble_primary_category', models.CharField(max_length=50, null=True)),
                ('rumble_secondary_category', models.CharField(max_length=50, null=True)),
                ('rumble_tags', models.CharField(max_length=200, null=True)),
                ('rumble_upload_date', models.DateTimeField(auto_now_add=True)),
                ('rumble_visibility', models.CharField(max_length=50, null=True)),
                ('rumble_video_file', models.FileField(null=True, upload_to='videos/')),
                ('rumble_thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_title', models.CharField(max_length=200)),
                ('youtube_video_description', models.TextField(null=True)),
                ('youtube_video_url', models.URLField(null=True)),
                ('youtube_channel', models.TextField(null=True)),
                ('youtube_view_count', models.BigIntegerField(null=True)),
                ('youtube_video_posted_date', models.DateField(null=True)),
                ('youtube_video_upload_date', models.DateTimeField(null=True)),
                ('youtube_video_file', models.FileField(null=True, upload_to='videos/')),
                ('youtube_video_thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
            ],
        ),
    ]
