# Generated by Django 3.2.25 on 2024-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
