# Generated by Django 3.2.25 on 2024-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0008_rename_rumble_tags_rumblevideo_rumble_rumble_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
