# Generated by Django 3.2.25 on 2024-05-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0009_alter_rumblevideo_rumble_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_file',
            field=models.FileField(max_length=255, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_file',
            field=models.FileField(max_length=255, null=True, upload_to='videos/'),
        ),
    ]
