# Generated by Django 3.2.25 on 2024-05-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0010_auto_20240530_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeurl',
            name='youtube_video_downloaded',
        ),
    ]
