# Generated by Django 3.2.25 on 2024-05-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0011_remove_youtubeurl_youtube_video_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeurl',
            name='youtube_video_date_downloaded',
        ),
    ]
