# Generated by Django 3.2.25 on 2024-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0012_remove_youtubeurl_youtube_video_date_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
