# Generated by Django 3.2.25 on 2024-06-22 21:52

from django.db import migrations, models
import rumble_uploader_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0013_youtubeurl_youtube_video_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_file',
            field=models.FileField(null=True, upload_to=rumble_uploader_app.models.dynamic_upload_path, validators=[rumble_uploader_app.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_thumbnail',
            field=models.FileField(null=True, upload_to=rumble_uploader_app.models.dynamic_upload_path, validators=[rumble_uploader_app.models.validate_file_type]),
        ),
    ]
