# Generated by Django 3.2.25 on 2024-06-23 01:25

from django.db import migrations, models
import rumble_uploader_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0014_auto_20240622_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', validators=[rumble_uploader_app.models.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_file',
            field=models.FileField(null=True, upload_to='videos/', validators=[rumble_uploader_app.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/', validators=[rumble_uploader_app.models.validate_image_type]),
        ),
    ]
