# Generated by Django 3.2.25 on 2024-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0015_auto_20240623_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_visibility',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
