# Generated by Django 3.2.25 on 2024-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0016_alter_rumblevideo_rumble_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_visibility',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
