# Generated by Django 3.2.25 on 2024-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0017_alter_rumblevideo_rumble_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_primary_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_secondary_category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
