# Generated by Django 3.2.25 on 2024-06-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0019_auto_20240626_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumblevideo',
            name='rumble_account',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
