# Generated by Django 3.2.25 on 2024-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0020_rumblevideo_rumble_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumblevideo',
            name='rumble_direct_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rumblevideo',
            name='rumble_embed_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rumblevideo',
            name='rumble_monetized_embed',
            field=models.TextField(null=True),
        ),
    ]
