# Generated by Django 3.2.25 on 2024-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0021_auto_20240708_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumblevideo',
            name='uploaded_to_rumble_success',
            field=models.BooleanField(default=False),
        ),
    ]
