# Generated by Django 3.2.25 on 2024-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0022_rumblevideo_uploaded_to_rumble_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
