# Generated by Django 3.2.25 on 2024-07-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0024_auto_20240712_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_account',
            field=models.CharField(blank=True, choices=[('randomrumblevideos', 'randomrumblevideos'), ('rumblearchives', 'rumblearchives'), ('therumblewarfootage', 'therumblewarfootage')], max_length=200, null=True),
        ),
    ]
