# Generated by Django 3.2.25 on 2024-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0026_auto_20240717_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_downloaded_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
