# Generated by Django 3.2.25 on 2024-07-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0027_youtubeurl_youtube_video_downloaded_successfully'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumblevideo',
            name='rumble_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('scheduled', 'Scheduled')], default='Private', max_length=100, null=True),
        ),
    ]
