# Generated by Django 3.2.25 on 2024-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0028_alter_rumblevideo_rumble_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
