# Generated by Django 3.2.25 on 2024-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0028_alter_rumblevideo_rumble_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_video_duration',
            field=models.DurationField(null=True),
        ),
    ]
