# Generated by Django 3.2.25 on 2024-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0029_youtubevideo_youtube_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_channel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_likes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_published_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_video_upload_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='youtube_view_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
