# Generated by Django 3.2.25 on 2024-07-31 12:53

from django.db import migrations, models
import rumble_uploader_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0029_youtubeurl_youtube_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/', validators=[rumble_uploader_app.models.validate_image_type]),
        ),
    ]
