# Generated by Django 3.2.25 on 2024-07-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0030_auto_20240730_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
