# Generated by Django 3.2.25 on 2024-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_uploader_app', '0031_alter_rumblevideo_rumble_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumblevideo',
            name='rumble_licensing_options',
            field=models.CharField(choices=[('rumble video_management exclusive', 'Rumble Video Management Exclusive'), ('rumble video_management non exclusive', 'Rumble Video Management Non Exclusive'), ('rumble video_management rumble only', 'Rumble Video Management Rumble Only')], default='Rumble Video Management Exclusive', max_length=100, null=True),
        ),
    ]
